[2025-02-01T17:25:07.075+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-01T17:25:07.176+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: INETUM_DAG.preprocess_data manual__2025-02-01T17:24:56.004150+00:00 [queued]>
[2025-02-01T17:25:07.204+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: INETUM_DAG.preprocess_data manual__2025-02-01T17:24:56.004150+00:00 [queued]>
[2025-02-01T17:25:07.205+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-01T17:25:07.247+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): preprocess_data> on 2025-02-01 17:24:56.004150+00:00
[2025-02-01T17:25:07.263+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=673) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T17:25:07.270+0000] {standard_task_runner.py:63} INFO - Started process 682 to run task
[2025-02-01T17:25:07.267+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'INETUM_DAG', 'preprocess_data', 'manual__2025-02-01T17:24:56.004150+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/inetum_dag.py', '--cfg-path', '/tmp/tmpafbvcjg_']
[2025-02-01T17:25:07.276+0000] {standard_task_runner.py:91} INFO - Job 176: Subtask preprocess_data
[2025-02-01T17:25:07.388+0000] {task_command.py:426} INFO - Running <TaskInstance: INETUM_DAG.preprocess_data manual__2025-02-01T17:24:56.004150+00:00 [running]> on host 2892ee60bb8a
[2025-02-01T17:25:07.602+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='INETUM_DAG' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T17:24:56.004150+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T17:24:56.004150+00:00'
[2025-02-01T17:25:07.607+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-01T17:25:07.629+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-01T17:25:07.630+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inetum_dag.py", line 35, in preprocess_data
    logging.info(f"Se extrajeron {len(articlesuniques)} art√≠culos de la API.")
    ^^^^^^^
NameError: name 'logging' is not defined. Did you forget to import 'logging'
[2025-02-01T17:25:07.660+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=INETUM_DAG, task_id=preprocess_data, execution_date=20250201T172456, start_date=20250201T172507, end_date=20250201T172507
[2025-02-01T17:25:07.683+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 176 for task preprocess_data (name 'logging' is not defined; 682)
[2025-02-01T17:25:07.732+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-01T17:25:07.779+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T17:25:07.783+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
