[2025-02-01T17:03:26.837+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-01T17:03:26.883+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: INETUM_DAG.extract_data manual__2025-02-01T17:03:20.707498+00:00 [queued]>
[2025-02-01T17:03:26.897+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: INETUM_DAG.extract_data manual__2025-02-01T17:03:20.707498+00:00 [queued]>
[2025-02-01T17:03:26.899+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-02-01T17:03:26.924+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): extract_data> on 2025-02-01 17:03:20.707498+00:00
[2025-02-01T17:03:26.934+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=410) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T17:03:26.938+0000] {standard_task_runner.py:63} INFO - Started process 412 to run task
[2025-02-01T17:03:26.938+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'INETUM_DAG', 'extract_data', 'manual__2025-02-01T17:03:20.707498+00:00', '--job-id', '172', '--raw', '--subdir', 'DAGS_FOLDER/inetum_dag.py', '--cfg-path', '/tmp/tmpowq7bn15']
[2025-02-01T17:03:26.943+0000] {standard_task_runner.py:91} INFO - Job 172: Subtask extract_data
[2025-02-01T17:03:27.041+0000] {task_command.py:426} INFO - Running <TaskInstance: INETUM_DAG.extract_data manual__2025-02-01T17:03:20.707498+00:00 [running]> on host 2892ee60bb8a
[2025-02-01T17:03:27.211+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andres Urrea' AIRFLOW_CTX_DAG_ID='INETUM_DAG' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T17:03:20.707498+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T17:03:20.707498+00:00'
[2025-02-01T17:03:27.217+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-01T17:03:27.218+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-01T17:03:27.220+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inetum_dag.py", line 15, in extract_data
    client_spaceflight = ExtractAPI()
                         ^^^^^^^^^^
NameError: name 'ExtractAPI' is not defined
[2025-02-01T17:03:27.251+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=INETUM_DAG, task_id=extract_data, execution_date=20250201T170320, start_date=20250201T170326, end_date=20250201T170327
[2025-02-01T17:03:27.282+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 172 for task extract_data (name 'ExtractAPI' is not defined; 412)
[2025-02-01T17:03:27.314+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-01T17:03:27.364+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T17:03:27.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
